// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: jobmanager.proto

// The jobmanager.v1 package includes the API for the first major
// version of the JobManager API.  This API can be extended with
// non-breaking changes. If breaking changes are required, then
// we can introduce new versions of the API alongside this one to
// maintain backward compatibility.

package jobmanagerv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JobManager_Start_FullMethodName        = "/jobmanager.v1.JobManager/Start"
	JobManager_Stop_FullMethodName         = "/jobmanager.v1.JobManager/Stop"
	JobManager_Query_FullMethodName        = "/jobmanager.v1.JobManager/Query"
	JobManager_List_FullMethodName         = "/jobmanager.v1.JobManager/List"
	JobManager_StreamOutput_FullMethodName = "/jobmanager.v1.JobManager/StreamOutput"
)

// JobManagerClient is the client API for JobManager service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The JobManager service models the API exposed by the JobManager.
type JobManagerClient interface {
	// Starts a new job.  The given JobCreationRequest captures the
	// details needed by the service to create the job.  Returns a
	// Job, that will enable further operations on the created job.
	Start(ctx context.Context, in *JobCreationRequest, opts ...grpc.CallOption) (*Job, error)
	// Terminates a (potentially running) Job by sending it the
	// SIGKILL signal.  If the specified job is no longer running,
	// this function has no effect.
	Stop(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*NilMessage, error)
	// Queries the state of the given Job.
	Query(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*JobStatus, error)
	// List all jobs and their status.  Possible extensions to this
	// might enable clients to specify a filter to reduce the
	// resulting set.  Depending on the desired scale of the system,
	// / paging might also be desired.
	List(ctx context.Context, in *NilMessage, opts ...grpc.CallOption) (*JobStatusList, error)
	// Streams the output of the running job to the client.
	// The stream begins with the initial output generated by the Job
	// and ends when the Job is finished.
	StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobOutput], error)
}

type jobManagerClient struct {
	cc grpc.ClientConnInterface
}

func NewJobManagerClient(cc grpc.ClientConnInterface) JobManagerClient {
	return &jobManagerClient{cc}
}

func (c *jobManagerClient) Start(ctx context.Context, in *JobCreationRequest, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, JobManager_Start_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobManagerClient) Stop(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*NilMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NilMessage)
	err := c.cc.Invoke(ctx, JobManager_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobManagerClient) Query(ctx context.Context, in *JobID, opts ...grpc.CallOption) (*JobStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatus)
	err := c.cc.Invoke(ctx, JobManager_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobManagerClient) List(ctx context.Context, in *NilMessage, opts ...grpc.CallOption) (*JobStatusList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobStatusList)
	err := c.cc.Invoke(ctx, JobManager_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jobManagerClient) StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[JobOutput], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &JobManager_ServiceDesc.Streams[0], JobManager_StreamOutput_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamOutputRequest, JobOutput]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobManager_StreamOutputClient = grpc.ServerStreamingClient[JobOutput]

// JobManagerServer is the server API for JobManager service.
// All implementations must embed UnimplementedJobManagerServer
// for forward compatibility.
//
// The JobManager service models the API exposed by the JobManager.
type JobManagerServer interface {
	// Starts a new job.  The given JobCreationRequest captures the
	// details needed by the service to create the job.  Returns a
	// Job, that will enable further operations on the created job.
	Start(context.Context, *JobCreationRequest) (*Job, error)
	// Terminates a (potentially running) Job by sending it the
	// SIGKILL signal.  If the specified job is no longer running,
	// this function has no effect.
	Stop(context.Context, *JobID) (*NilMessage, error)
	// Queries the state of the given Job.
	Query(context.Context, *JobID) (*JobStatus, error)
	// List all jobs and their status.  Possible extensions to this
	// might enable clients to specify a filter to reduce the
	// resulting set.  Depending on the desired scale of the system,
	// / paging might also be desired.
	List(context.Context, *NilMessage) (*JobStatusList, error)
	// Streams the output of the running job to the client.
	// The stream begins with the initial output generated by the Job
	// and ends when the Job is finished.
	StreamOutput(*StreamOutputRequest, grpc.ServerStreamingServer[JobOutput]) error
	mustEmbedUnimplementedJobManagerServer()
}

// UnimplementedJobManagerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJobManagerServer struct{}

func (UnimplementedJobManagerServer) Start(context.Context, *JobCreationRequest) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Start not implemented")
}
func (UnimplementedJobManagerServer) Stop(context.Context, *JobID) (*NilMessage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedJobManagerServer) Query(context.Context, *JobID) (*JobStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedJobManagerServer) List(context.Context, *NilMessage) (*JobStatusList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedJobManagerServer) StreamOutput(*StreamOutputRequest, grpc.ServerStreamingServer[JobOutput]) error {
	return status.Errorf(codes.Unimplemented, "method StreamOutput not implemented")
}
func (UnimplementedJobManagerServer) mustEmbedUnimplementedJobManagerServer() {}
func (UnimplementedJobManagerServer) testEmbeddedByValue()                    {}

// UnsafeJobManagerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JobManagerServer will
// result in compilation errors.
type UnsafeJobManagerServer interface {
	mustEmbedUnimplementedJobManagerServer()
}

func RegisterJobManagerServer(s grpc.ServiceRegistrar, srv JobManagerServer) {
	// If the following call pancis, it indicates UnimplementedJobManagerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JobManager_ServiceDesc, srv)
}

func _JobManager_Start_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobCreationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobManagerServer).Start(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobManager_Start_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobManagerServer).Start(ctx, req.(*JobCreationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobManager_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobManagerServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobManager_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobManagerServer).Stop(ctx, req.(*JobID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobManager_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobManagerServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobManager_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobManagerServer).Query(ctx, req.(*JobID))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobManager_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NilMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JobManagerServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JobManager_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JobManagerServer).List(ctx, req.(*NilMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _JobManager_StreamOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(JobManagerServer).StreamOutput(m, &grpc.GenericServerStream[StreamOutputRequest, JobOutput]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type JobManager_StreamOutputServer = grpc.ServerStreamingServer[JobOutput]

// JobManager_ServiceDesc is the grpc.ServiceDesc for JobManager service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobManager_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "jobmanager.v1.JobManager",
	HandlerType: (*JobManagerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Start",
			Handler:    _JobManager_Start_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _JobManager_Stop_Handler,
		},
		{
			MethodName: "Query",
			Handler:    _JobManager_Query_Handler,
		},
		{
			MethodName: "List",
			Handler:    _JobManager_List_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOutput",
			Handler:       _JobManager_StreamOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "jobmanager.proto",
}
